import { useEffect, useState } from 'react';
import { api } from '../api';

interface Props {
  entityId: string;
}

export function NarrativePanel({ entityId }: Props) {
  const [narrative, setNarrative] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    api.narrative(entityId).then((d) => {
      setNarrative(d.narrative);
      setLoading(false);
    }).catch(() => {
      setNarrative('Narrative unavailable.');
      setLoading(false);
    });
  }, [entityId]);

  if (loading) {
    return (
      <div className="bg-[var(--eve-surface)] border border-[var(--eve-border)] rounded-lg p-4">
        <div className="flex items-center gap-2 text-[var(--eve-dim)] text-sm">
          <span className="animate-pulse">Generating intelligence briefing...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-[var(--eve-surface)] border border-[var(--eve-border)] rounded-lg p-4 space-y-2">
      <h3 className="text-xs uppercase tracking-wider text-[var(--eve-orange)] font-bold">
        Intelligence Briefing
      </h3>
      <div className="text-sm text-[var(--eve-text)] leading-relaxed whitespace-pre-line">
        {narrative}
      </div>
      <div className="text-[10px] text-[var(--eve-dim)] pt-1 border-t border-[var(--eve-border)]">
        Generated by WatchTower AI from on-chain evidence
      </div>
    </div>
  );
}
