"""Warden — autonomous threat hypothesis loop.

Ingests events → generates hypotheses → evaluates against doctrine →
commits or discards → audits. Runs as background task alongside poller.

NEVER CRASHES. All errors logged and continued.
"""

import json
import time
from dataclasses import dataclass, field
from pathlib import Path

from backend.core.config import settings
from backend.core.logger import get_logger
from backend.db.database import get_db

logger = get_logger("warden")

AUDIT_PATH = Path("data/warden_audit.jsonl")

# Doctrine weights for hypothesis scoring
WEIGHTS = {
    "evidence": 0.35,
    "recency": 0.25,
    "impact": 0.25,
    "novelty": 0.15,
}

COMMIT_THRESHOLD = 0.5
OPERATOR_ALERT_THRESHOLD = 0.8


@dataclass
class Hypothesis:
    """A single threat hypothesis generated by the Warden."""

    category: str  # THREAT, LOGISTICS, INTEL
    title: str
    description: str
    evidence_count: int = 0
    evidence_summary: str = ""
    scores: dict[str, float] = field(default_factory=dict)
    composite: float = 0.0
    committed: bool = False
    zone_id: str = ""
    entity_id: str = ""

    def score(self, evidence: float, recency: float, impact: float, novelty: float) -> float:
        """Score hypothesis against doctrine weights. Returns composite 0.0-1.0."""
        self.scores = {
            "evidence": min(1.0, max(0.0, evidence)),
            "recency": min(1.0, max(0.0, recency)),
            "impact": min(1.0, max(0.0, impact)),
            "novelty": min(1.0, max(0.0, novelty)),
        }
        self.composite = sum(self.scores[k] * WEIGHTS[k] for k in WEIGHTS)
        return self.composite

    def to_dict(self) -> dict:
        return {
            "category": self.category,
            "title": self.title,
            "description": self.description,
            "evidence_count": self.evidence_count,
            "evidence_summary": self.evidence_summary,
            "scores": self.scores,
            "composite": round(self.composite, 3),
            "committed": self.committed,
            "zone_id": self.zone_id,
            "entity_id": self.entity_id,
        }


def _audit_log(hypothesis: Hypothesis, action: str) -> None:
    """Append-only audit log. Sacred — never truncated."""
    AUDIT_PATH.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "timestamp": int(time.time()),
        "action": action,
        "hypothesis": hypothesis.to_dict(),
    }
    try:
        with open(AUDIT_PATH, "a") as f:
            f.write(json.dumps(entry) + "\n")
    except Exception as e:
        logger.error("Audit log write failed: %s", e)


async def _notify_operator(hypothesis: Hypothesis) -> None:
    """Fire Discord webhook for high-confidence THREAT findings."""
    webhook_url = settings.DISCORD_WEBHOOK_URL
    if not webhook_url:
        return

    try:
        from backend.analysis.oracle import EVE_ORANGE, EVE_RED, fire_webhook

        color = EVE_RED if hypothesis.category == "THREAT" else EVE_ORANGE
        await fire_webhook(
            webhook_url,
            f"WARDEN: {hypothesis.title}",
            (
                f"{hypothesis.description}\n\n"
                f"**Evidence**: {hypothesis.evidence_summary}\n"
                f"**Confidence**: {hypothesis.composite:.0%}"
            ),
            color,
        )
    except Exception as e:
        logger.error("Operator notification failed: %s", e)


# ---------- Hypothesis Generators ----------
# Each returns a list of Hypothesis objects from current database state.


def _hypothesize_feral_escalation() -> list[Hypothesis]:
    """Detect zones with escalating feral AI tiers."""
    db = get_db()
    now = int(time.time())
    hypotheses = []

    # Zones that escalated in the last 6 hours
    escalations = db.execute(
        """SELECT zone_id, COUNT(*) as evt_count,
                  MIN(old_tier) as start_tier, MAX(new_tier) as end_tier,
                  MIN(timestamp) as first_ts, MAX(timestamp) as last_ts
           FROM feral_ai_events
           WHERE event_type = 'evolution' AND timestamp > ?
           GROUP BY zone_id
           ORDER BY end_tier DESC""",
        (now - 21600,),
    ).fetchall()

    for esc in escalations:
        zone = db.execute(
            "SELECT name, last_scanned FROM orbital_zones WHERE zone_id = ?",
            (esc["zone_id"],),
        ).fetchone()
        zone_name = zone["name"] if zone else esc["zone_id"][:16]

        # Multi-step escalation is more dangerous
        tier_delta = esc["end_tier"] - esc["start_tier"]
        time_span = max(1, esc["last_ts"] - esc["first_ts"])
        rate = tier_delta / (time_span / 3600)  # tiers per hour

        h = Hypothesis(
            category="THREAT",
            title=f"Feral AI escalation: {zone_name}",
            description=(
                f"Zone {zone_name} escalated from tier {esc['start_tier']} "
                f"to tier {esc['end_tier']} ({esc['evt_count']} events). "
                f"Rate: {rate:.1f} tiers/hour."
            ),
            evidence_count=esc["evt_count"],
            zone_id=esc["zone_id"],
        )

        # Score
        evidence = min(1.0, esc["evt_count"] / 5)
        recency = max(0.0, 1.0 - (now - esc["last_ts"]) / 21600)
        impact = min(1.0, esc["end_tier"] / 3)
        # Novel if rapid escalation
        novelty = min(1.0, rate) if rate > 0.5 else 0.2
        h.score(evidence, recency, impact, novelty)

        # Check scan coverage
        last_scanned = zone["last_scanned"] if zone else None
        scan_gap = (now - last_scanned) if last_scanned else 9999
        if scan_gap > 1200:
            h.evidence_summary = (
                f"Tier {esc['start_tier']}→{esc['end_tier']}, UNSCANNED {scan_gap // 60}m"
            )
        else:
            h.evidence_summary = (
                f"Tier {esc['start_tier']}→{esc['end_tier']}, scanned {scan_gap // 60}m ago"
            )

        hypotheses.append(h)

    return hypotheses


def _hypothesize_kill_clusters() -> list[Hypothesis]:
    """Detect systems with unusual kill concentration."""
    db = get_db()
    now = int(time.time())
    hypotheses = []

    # Kill counts by system in last 2 hours
    clusters = db.execute(
        """SELECT solar_system_id, COUNT(*) as kills,
                  MIN(timestamp) as first_kill, MAX(timestamp) as last_kill
           FROM killmails
           WHERE timestamp > ? AND solar_system_id != ''
           GROUP BY solar_system_id
           HAVING kills >= 3
           ORDER BY kills DESC
           LIMIT 10""",
        (now - 7200,),
    ).fetchall()

    # Get baseline (average kills per system over 24h)
    baseline_row = db.execute(
        """SELECT COUNT(*) as total, COUNT(DISTINCT solar_system_id) as systems
           FROM killmails WHERE timestamp > ?""",
        (now - 86400,),
    ).fetchone()
    baseline = baseline_row["total"] / max(1, baseline_row["systems"]) if baseline_row else 1

    for cluster in clusters:
        ratio = cluster["kills"] / max(1, baseline)
        if ratio < 2.0:
            continue  # Not significantly above baseline

        h = Hypothesis(
            category="THREAT",
            title=f"Kill cluster: system {cluster['solar_system_id'][:16]}",
            description=(
                f"{cluster['kills']} kills in 2 hours "
                f"({ratio:.1f}x baseline). "
                f"Active window: {(cluster['last_kill'] - cluster['first_kill']) // 60}m."
            ),
            evidence_count=cluster["kills"],
            evidence_summary=f"{cluster['kills']} kills, {ratio:.1f}x normal",
        )

        evidence = min(1.0, cluster["kills"] / 10)
        recency = max(0.0, 1.0 - (now - cluster["last_kill"]) / 7200)
        impact = min(1.0, ratio / 5)
        novelty = 0.5 if ratio > 3 else 0.2
        h.score(evidence, recency, impact, novelty)

        hypotheses.append(h)

    return hypotheses


def _hypothesize_blind_spots() -> list[Hypothesis]:
    """Detect expanding scan coverage gaps."""
    db = get_db()
    now = int(time.time())
    hypotheses = []

    # Zones unscanned for >30 minutes with feral AI tier > 0
    blind = db.execute(
        """SELECT zone_id, name, feral_ai_tier, last_scanned
           FROM orbital_zones
           WHERE feral_ai_tier > 0
           AND (last_scanned IS NULL OR last_scanned < ?)
           ORDER BY feral_ai_tier DESC""",
        (now - 1800,),
    ).fetchall()

    if len(blind) < 2:
        return hypotheses

    # Group finding — multiple blind spots is worse than one
    zone_names = [z["name"] or z["zone_id"][:12] for z in blind[:5]]
    max_tier = max(z["feral_ai_tier"] for z in blind)
    worst_gap = max((now - z["last_scanned"]) if z["last_scanned"] else 9999 for z in blind)

    h = Hypothesis(
        category="THREAT",
        title=f"Expanding blind spots ({len(blind)} zones)",
        description=(
            f"{len(blind)} active feral AI zones unscanned >30m. "
            f"Highest tier: {max_tier}. "
            f"Worst gap: {worst_gap // 60}m. "
            f"Zones: {', '.join(zone_names)}."
        ),
        evidence_count=len(blind),
        evidence_summary=f"{len(blind)} zones, max tier {max_tier}, worst gap {worst_gap // 60}m",
    )

    evidence = min(1.0, len(blind) / 5)
    recency = 1.0  # By definition, this is current
    impact = min(1.0, max_tier / 3)
    novelty = 0.3
    h.score(evidence, recency, impact, novelty)
    hypotheses.append(h)

    return hypotheses


def _hypothesize_clone_depletion() -> list[Hypothesis]:
    """Detect clone reserve depletion trends."""
    db = get_db()
    hypotheses = []

    # Owners with declining clone counts
    owners = db.execute(
        """SELECT owner_id, owner_name, COUNT(*) as active
           FROM clones WHERE status = 'active'
           GROUP BY owner_id
           HAVING active <= 3
           ORDER BY active ASC""",
    ).fetchall()

    # Check manufacturing queue depth
    queue_depth = db.execute(
        "SELECT COUNT(*) as cnt FROM clones WHERE status = 'manufacturing'"
    ).fetchone()
    queue = queue_depth["cnt"] if queue_depth else 0

    if not owners:
        return hypotheses

    names = [o["owner_name"] or o["owner_id"][:12] for o in owners[:5]]
    min_active = min(o["active"] for o in owners)

    h = Hypothesis(
        category="LOGISTICS",
        title=f"Clone reserves critical ({len(owners)} owners)",
        description=(
            f"{len(owners)} owner(s) at 3 or fewer active clones. "
            f"Lowest: {min_active}. Queue depth: {queue}. "
            f"Affected: {', '.join(names)}."
        ),
        evidence_count=len(owners),
        evidence_summary=f"{len(owners)} owners low, min {min_active}, queue {queue}",
    )

    evidence = min(1.0, len(owners) / 3)
    recency = 1.0
    impact = 0.8 if min_active <= 1 else 0.5
    novelty = 0.2
    h.score(evidence, recency, impact, novelty)
    hypotheses.append(h)

    return hypotheses


def _hypothesize_hunting_patterns() -> list[Hypothesis]:
    """Detect entities with predictable hunting routes."""
    db = get_db()
    now = int(time.time())
    hypotheses = []

    # Top killers in last 12 hours
    killers = db.execute(
        """SELECT victim_character_id, COUNT(*) as kills
           FROM killmails WHERE timestamp > ?
           GROUP BY victim_character_id
           HAVING kills >= 3
           ORDER BY kills DESC LIMIT 5""",
        (now - 43200,),
    ).fetchall()

    # Check if they operate in limited systems (predictable)
    for killer in killers:
        systems = db.execute(
            """SELECT DISTINCT solar_system_id FROM killmails
               WHERE victim_character_id = ? AND timestamp > ?""",
            (killer["victim_character_id"], now - 43200),
        ).fetchall()

        system_count = len(systems)
        if system_count > 3:
            continue  # Too spread out to be predictable

        entity = db.execute(
            "SELECT display_name FROM entities WHERE entity_id = ?",
            (killer["victim_character_id"],),
        ).fetchone()
        name = entity["display_name"] if entity else killer["victim_character_id"][:16]

        h = Hypothesis(
            category="INTEL",
            title=f"Predictable victim pattern: {name}",
            description=(
                f"{name} died {killer['kills']} times in {system_count} system(s) "
                f"over the last 12 hours. Likely a camped route."
            ),
            evidence_count=killer["kills"],
            evidence_summary=f"{killer['kills']} deaths in {system_count} systems",
            entity_id=killer["victim_character_id"],
        )

        evidence = min(1.0, killer["kills"] / 5)
        recency = 0.8
        impact = 0.4
        novelty = 0.6 if system_count == 1 else 0.3
        h.score(evidence, recency, impact, novelty)
        hypotheses.append(h)

    return hypotheses


# ---------- Main Loop ----------

ALL_GENERATORS = [
    _hypothesize_feral_escalation,
    _hypothesize_kill_clusters,
    _hypothesize_blind_spots,
    _hypothesize_clone_depletion,
    _hypothesize_hunting_patterns,
]


async def run_warden_cycle() -> list[Hypothesis]:
    """Run one warden cycle: generate → score → commit/discard → audit.

    Returns committed hypotheses.
    """
    committed: list[Hypothesis] = []

    for generator in ALL_GENERATORS:
        try:
            hypotheses = generator()
        except Exception as e:
            logger.error("Hypothesis generator %s failed: %s", generator.__name__, e)
            continue

        for h in hypotheses:
            if h.composite >= COMMIT_THRESHOLD:
                h.committed = True
                _audit_log(h, "commit")
                committed.append(h)

                # Notify operator on high-confidence threats
                if h.category == "THREAT" and h.composite >= OPERATOR_ALERT_THRESHOLD:
                    try:
                        await _notify_operator(h)
                    except Exception as e:
                        logger.error("Operator notify failed: %s", e)
            else:
                _audit_log(h, "discard")
                logger.debug("Discarded: %s (%.2f)", h.title, h.composite)

    if committed:
        logger.info(
            "Warden cycle: %d committed, categories: %s",
            len(committed),
            ", ".join(set(h.category for h in committed)),
        )

        # Write to story_feed for frontend visibility (dedup: same title within 1 hour)
        try:
            db = get_db()
            now = int(time.time())
            for h in committed:
                existing = db.execute(
                    "SELECT id FROM story_feed WHERE headline = ? AND timestamp > ?",
                    (h.title, now - 3600),
                ).fetchone()
                if existing:
                    continue
                db.execute(
                    """INSERT INTO story_feed
                       (event_type, headline, body, entity_ids, severity, timestamp)
                       VALUES (?, ?, ?, ?, ?, ?)""",
                    (
                        f"warden_{h.category.lower()}",
                        h.title,
                        h.description,
                        json.dumps([h.entity_id or h.zone_id]),
                        "critical" if h.composite >= 0.8 else "warning",
                        now,
                    ),
                )
            db.commit()
        except Exception as e:
            logger.error("Story feed write failed: %s", e)

    return committed


async def run_warden(
    max_iterations: int = 10,
    max_duration_hours: int = 24,
    interval_seconds: int = 300,
) -> None:
    """Main warden loop. Runs for up to max_duration_hours.

    NEVER CRASHES. All errors logged and continued.
    """
    import asyncio

    logger.info(
        "Warden starting — max %d iterations, %dh duration, %ds interval",
        max_iterations,
        max_duration_hours,
        interval_seconds,
    )

    start = time.time()
    max_duration = max_duration_hours * 3600
    iteration = 0

    while iteration < max_iterations:
        elapsed = time.time() - start
        if elapsed >= max_duration:
            logger.info("Warden session expired after %.1fh", elapsed / 3600)
            break

        try:
            committed = await run_warden_cycle()
            iteration += 1
            logger.info(
                "Warden iteration %d/%d — %d findings (%.1fh elapsed)",
                iteration,
                max_iterations,
                len(committed),
                elapsed / 3600,
            )
        except Exception as e:
            logger.critical("Warden cycle error (continuing): %s", e)

        await asyncio.sleep(interval_seconds)

    logger.info(
        "Warden session complete — %d iterations in %.1fh",
        iteration,
        (time.time() - start) / 3600,
    )
